/// Firebase configuration.
///
/// Hand-written rather than generated by `flutterfire configure`, so that
/// adding the cloud never required installing the Firebase CLI onto the
/// machine that has to build the demo tomorrow morning.
///
/// ─────────────────────────────────────────────────────────────────────────
///  WIRED to the live project `bioguard-c75cc` (26.08).
///
///  These are CLIENT-SIDE values and are meant to ship inside the app — an
///  apiKey here is a project identifier, not a secret, and grants nothing on
///  its own. What actually guards the data is the Firestore security rules.
///  The thing that IS secret is the service-account key the bridge uses; it
///  lives at ~/.bioguard/service-account.json, outside the repo, and must
///  never appear in this file or any other tracked file.
///
///  To repoint at a different project, replace the six values below and
///  rebuild with:  flutter build web --release --base-href /app/
/// ─────────────────────────────────────────────────────────────────────────
///
/// With the placeholders left empty the app is still fully functional: the
/// Fleet tab reads the bridge's /cloud/api/fleet instead, which serves the
/// identical shape. Nothing crashes, nothing is stubbed out — it just reads
/// the fleet over the LAN rather than over the internet.
library;

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static const _web = FirebaseOptions(
    apiKey: 'AIzaSyBpqru4stmQ4mVKB06nkt8kSnZrpleYdLU',
    appId: '1:199283265474:web:12a3c86616bd6bfe02505b',
    messagingSenderId: '199283265474',
    projectId: 'bioguard-c75cc',
    authDomain: 'bioguard-c75cc.firebaseapp.com',
    storageBucket: 'bioguard-c75cc.firebasestorage.app'
  );

  /// Android and iOS reuse the web values here. A real release would carry
  /// google-services.json / GoogleService-Info.plist per platform; for a
  /// Firestore read against a test-mode database the web config is enough,
  /// and it keeps the demo to one place to edit.
  static FirebaseOptions get currentPlatform => _web;

  static String get projectId => _web.projectId;

  /// Whether a real project has been pasted in. FleetService checks this
  /// before touching Firebase, so an unconfigured build never pays the
  /// initialisation timeout.
  static bool get configured => _web.apiKey.isNotEmpty && _web.projectId.isNotEmpty;
}
