/// Firebase configuration.
///
/// Hand-written rather than generated by `flutterfire configure`, so that
/// adding the cloud never required installing the Firebase CLI onto the
/// machine that has to build the demo tomorrow morning.
///
/// ─────────────────────────────────────────────────────────────────────────
///  WIRED to the live project `bioguard-c75cc` (26.08).
///
///  These are CLIENT-SIDE values and are meant to ship inside the app — an
///  apiKey here is a project identifier, not a secret, and grants nothing on
///  its own. What actually guards the data is the Firestore security rules,
///  which now live in ../../firestore.rules (added 03.09.2026, after the
///  project was found still running on hackathon test-mode rules — public
///  read AND write). GitHub's secret-scanning alerts on the two keys below
///  are expected and are not a leak.
///  The thing that IS secret is the service-account key the bridge uses; it
///  lives at ~/.bioguard/service-account.json, outside the repo, and must
///  never appear in this file or any other tracked file.
///
///  To repoint at a different project, replace the six values below and
///  rebuild with:  flutter build web --release --base-href /app/
/// ─────────────────────────────────────────────────────────────────────────
///
/// With the placeholders left empty the app is still fully functional: the
/// Fleet tab reads the bridge's /cloud/api/fleet instead, which serves the
/// identical shape. Nothing crashes, nothing is stubbed out — it just reads
/// the fleet over the LAN rather than over the internet.
library;

import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static const _web = FirebaseOptions(
    apiKey: 'AIzaSyBpqru4stmQ4mVKB06nkt8kSnZrpleYdLU',
    appId: '1:199283265474:web:12a3c86616bd6bfe02505b',
    messagingSenderId: '199283265474',
    projectId: 'bioguard-c75cc',
    authDomain: 'bioguard-c75cc.firebaseapp.com',
    storageBucket: 'bioguard-c75cc.firebasestorage.app'
  );

  /// iOS needs its OWN app registration — it cannot borrow the web values.
  /// The native SDK validates the shape of GOOGLE_APP_ID and raises an
  /// Objective-C NSException on a `:web:` id ("Configuration fails. It may be
  /// caused by an invalid GOOGLE_APP_ID…"). That exception crosses no Dart
  /// boundary, so no try/catch around initializeApp can save the process — the
  /// app dies on launch. Leave these empty until an iOS app exists in the
  /// Firebase console; empty means [configured] is false on iOS and the Fleet
  /// tab reads the bridge instead, which is a working path, not a stub.
  static const _ios = FirebaseOptions(
    apiKey: 'AIzaSyAWY581hvEUu2VpYZItYHDXkqlPbKEGMKM',
    appId: '1:199283265474:ios:9c7b02bfb2dee1ef02505b',
    messagingSenderId: '199283265474',
    projectId: 'bioguard-c75cc',
    storageBucket: 'bioguard-c75cc.firebasestorage.app',
    iosBundleId: 'com.alp.strajer.strajerApp',
  );

  /// Android tolerates the web values today, but for the same reason as iOS it
  /// deserves its own registration before anyone ships it.
  static FirebaseOptions? get _platform {
    if (kIsWeb) return _web;
    return switch (defaultTargetPlatform) {
      TargetPlatform.iOS => _ios.appId.isEmpty ? null : _ios,
      TargetPlatform.android => _web,
      _ => null,
    };
  }

  /// Only read after [configured] has been checked.
  static FirebaseOptions get currentPlatform => _platform ?? _web;

  static String get projectId => _web.projectId;

  /// Whether THIS platform has a usable registration. FleetService checks it
  /// before touching Firebase, so a platform without one never initialises —
  /// and never crashes on a mismatched app id.
  static bool get configured {
    final o = _platform;
    return o != null && o.apiKey.isNotEmpty && o.projectId.isNotEmpty;
  }
}
