/// Firebase configuration.
///
/// Hand-written rather than generated by `flutterfire configure`, so that
/// adding the cloud never required installing the Firebase CLI onto the
/// machine that has to build the demo tomorrow morning.
///
/// ─────────────────────────────────────────────────────────────────────────
///  TO CONNECT THE REAL PROJECT — paste four values and rebuild:
///
///  Firebase console -> your project -> ⚙ Project settings -> General
///    -> "Your apps" -> Web app (</>) -> "SDK setup and configuration"
///
///  Copy apiKey, appId, messagingSenderId, projectId into _web below.
///  `configured` flips to true automatically once apiKey is non-empty.
/// ─────────────────────────────────────────────────────────────────────────
///
/// With the placeholders left empty the app is still fully functional: the
/// Fleet tab reads the bridge's /cloud/api/fleet instead, which serves the
/// identical shape. Nothing crashes, nothing is stubbed out — it just reads
/// the fleet over the LAN rather than over the internet.
library;

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static const _web = FirebaseOptions(
    apiKey: '',                 // <- paste
    appId: '',                  // <- paste
    messagingSenderId: '',      // <- paste
    projectId: '',              // <- paste
    authDomain: '',             // optional: <projectId>.firebaseapp.com
    storageBucket: '',          // optional: <projectId>.firebasestorage.app
  );

  /// Android and iOS reuse the web values here. A real release would carry
  /// google-services.json / GoogleService-Info.plist per platform; for a
  /// Firestore read against a test-mode database the web config is enough,
  /// and it keeps the demo to one place to edit.
  static FirebaseOptions get currentPlatform => _web;

  static String get projectId => _web.projectId;

  /// Whether a real project has been pasted in. FleetService checks this
  /// before touching Firebase, so an unconfigured build never pays the
  /// initialisation timeout.
  static bool get configured => _web.apiKey.isNotEmpty && _web.projectId.isNotEmpty;
}
